### ISSUE TITLE
Config option to create namespace if not exists

### ISSUE THREAD

**Issue by CluEleSsUK** [DNXLabs/terraform-aws-eks-argocd#1]
Presently, there is a config option to optionally create the namespace.  If this is set to true and a previous deploy has already happened, the terraform job blows up.  If set to false and a deploy has not yet happened, the namespace doesn't yet exist and blows up.

It'd be great if I could create it when it doesn't exist and ignore it when it already exists!

**Comment by arthurbdiniz** [comment]
Hi @CluEleSsUK. 

I get your point of validating the namespace before deploying the chart but due to some limitations on the terraform namespace resource the only way of doing this is by using workarounds with bash and other tools. 
https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/namespace

So the recommendation is if a previous deployment has already happened, set the variable `create_namespace` to false when creating the next deploy.

Another alternative is to always set `create_namespace` to `false` and bring the namespace creation logic outside the module, making the module depends on this `kubernetes_namespace` resource before deploying the modules.
