### ISSUE TITLE
Manual deletion of resources is not resynced by terraform

### ISSUE THREAD

**Issue by CluEleSsUK** [DNXLabs/terraform-aws-eks-argocd#3]
After I delete some (or all) of the things running in the argocd namespace, rerunning my job with this terraform provider suggests `No changes. Your infrastructure matches the configuration.`.  Perhaps I've missed the point, but my expectation was that this provider would restore all the argocd resources if nuked?

**Comment by arthurbdiniz** [comment]
Hi @CluEleSsUK, if you run this module to deploy things inside a cluster you shouldn't `edit` or `remove` resources manually using `kubectl` or any other tool. The problem is that terraform stores the state of the deployment to keep track of resources to remove, change or add. And if you remove manually, terraform lost this track.

But hopefully, you can:
1. Set the variable `enabled = false` and run ` terraform init, terraform plan, terraform apply` and then re-enabled it. (this should recreate correctly the TF state file. 
2. Delete the terraform state for just this module using `terraform state rm <module_name>` and run ` terraform init, terraform plan, terraform apply`.
